
#ifndef __IMU_CMD_H__
#define __IMU_CMD_H__


typedef enum
{
    IMU_NOCMD = 0,
    IMU_CMD_MIN = IMU_NOCMD, 
    IMU_SELECT_MAGNETOMETER,
    IMU_SELECT_GYROSCOPE,
    IMU_SELECT_ACCELEROMETER,
    IMU_SELECT_AHRS,
    IMU_SENSOR_CALIBRATE_NORMALIZED,
    IMU_SENSOR_CALIBRATE_ZERO_OFFSET,
    IMU_SENSOR_CALIBRATE_MAGNETOMETER,
    IMU_SENSOR_CALIBRATE_GYROSCOPE,
    IMU_SENSOR_CALIBRATE_RESET,
    IMU_SENSOR_CALIBRATE_SAVE,
    IMU_AHRS_INPUT_TOGGLE,
    IMU_AHRS_YAW_TOGGLE,
    IMU_AHRS_PITCH_TOGGLE,
    IMU_AHRS_ROLL_TOGGLE,
    IMU_SENSOR_DATA_HOLD_TOGGLE,
    IMU_SENSOR_DATA_IDEAL_TOGGLE,
    IMU_SENSOR_DATA_FIXED_TOGGLE,
    IMU_SENSOR_DATA_DISPLAY_TOGGLE,
    IMU_AHRS_PROP_GAIN_UP,
    IMU_AHRS_PROP_GAIN_DOWN,
    IMU_AHRS_INTEG_GAIN_UP,
    IMU_AHRS_INTEG_GAIN_DOWN,
    IMU_AHRS_SAMPLE_FREQ_UP,
    IMU_AHRS_SAMPLE_FREQ_DOWN,
    IMU_GYROSCOPE_CORRECTION_UP,
    IMU_GYROSCOPE_CORRECTION_DOWN,
    IMU_MAGNETOMETER_STABILITY_TOGGLE,
    IMU_AHRS_BETA_GAIN_UP,
    IMU_AHRS_BETA_GAIN_DOWN,
    IMU_AHRS_ALGORITHM_TOGGLE,
    IMU_GYROSCOPE_ENABLE_TOGGLE,
    IMU_UNCALIBRATED_DISPLAY_TOGGLE,
    IMU_SETTINGS_DISPLAY_TOGGLE,
    IMU_SELECT_ODR,
    IMU_CMD_MAX = IMU_SELECT_ODR
} IMU_CMD_t;

typedef enum
{
    IMU_AHRS = 0,
    IMU_SENSOR_MIN = IMU_AHRS,
    IMU_ACCELEROMETER,
    IMU_GYROSCOPE,
    IMU_MAGNETOMETER,
    IMU_ODR,
    IMU_SENSOR_MAX = IMU_ODR
} IMU_SENSOR_t;

#endif


